# Auto Analyze - 一键全自动分析脚本

> 整合所有分析步骤，一键完成APK分析流程

```powershell
param(
    [Parameter(Mandatory=$true)][string]$ApkPath,
    [string]$OutputDir,
    [switch]$SkipStatic,
    [switch]$SkipDynamic,
    [switch]$AutoInject,
    [string]$FridaScript,
    [switch]$GenerateReport
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'

$SkillRoot = "C:\Users\wyx\.claude\skills\WYX"
$Timestamp = Get-Date -Format "yyyyMMdd-HHmmss"

Write-Host "[*] WYX Auto Analyzer v1.0" -ForegroundColor Cyan
Write-Host "[*] Target: $ApkPath" -ForegroundColor Yellow
Write-Host "[*] Timestamp: $Timestamp" -ForegroundColor Yellow

# 准备输出目录
if (-not $OutputDir) {
    $OutputDir = Join-Path (Split-Path $ApkPath -Parent) "analysis_$Timestamp"
}
New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
Write-Host "`n[*] Output directory: $OutputDir" -ForegroundColor Green

# ==================== Phase 0: 解密APK ====================
Write-Host "`n[Phase 0] Decrypting APK..." -ForegroundColor Cyan

$decodeScript = Join-Path $SkillRoot "scripts\decode.ps1"
if (Test-Path $decodeScript) {
    $decodeOutput = pwsh -File $decodeScript -ApkPath $ApkPath -OutRoot $OutputDir 2>&1
    Write-Host $decodeOutput
} else {
    Write-Host "[!] decode.ps1 not found" -ForegroundColor Red
    exit 1
}

# 获取输出路径
$jadxOut = Join-Path $OutputDir "jadx"
$apktoolOut = Join-Path $OutputDir "apktool"

# ==================== Phase 1: 静态分析 ====================
if (-not $SkipStatic) {
    Write-Host "`n[Phase 1] Static Analysis..." -ForegroundColor Cyan

    # 1.1 Manifest分析
    $manifestScript = Join-Path $SkillRoot "scripts\manifest-summary.ps1"
    if (Test-Path $manifestScript) {
        $manifestPath = Join-Path $apktoolOut "AndroidManifest.xml"
        if (Test-Path $manifestPath) {
            pwsh -File $manifestScript -ManifestPath $manifestPath
        }
    }

    # 1.2 关键逻辑搜索
    $searchScript = Join-Path $SkillRoot "scripts\search-logic.ps1"
    if (Test-Path $searchScript) {
        if (Test-Path $jadxOut) {
            Write-Host "`n[*] Searching for critical logic..." -ForegroundColor Yellow
            pwsh -File $searchScript -SourceDir $jadxOut -Keywords @("license","auth","key","verify","sign","encrypt","decrypt","login","password")
        }
    }

    # 1.3 判断是否有Native库
    $soFiles = Get-ChildItem $apktoolOut -Recurse -Filter "*.so" -ErrorAction SilentlyContinue
    if ($soFiles.Count -gt 0) {
        Write-Host "`n[!] Native libraries detected ($($soFiles.Count))" -ForegroundColor Yellow
        Write-Host "    Consider using ida-reverse skill for deep analysis" -ForegroundColor Gray
    }
}

# ==================== Phase 2: 动态分析 ====================
if (-not $SkipDynamic -and $AutoInject) {
    Write-Host "`n[Phase 2] Dynamic Analysis with Frida..." -ForegroundColor Cyan

    if (-not $FridaScript) {
        # 自动生成绕过脚本
        $bypassScript = Join-Path $OutputDir "auto_bypass.js"
        Write-Host "[*] Generating auto-bypass script..." -ForegroundColor Yellow

        $bypassContent = @"
// Auto-generated bypass script by WYX
Java.perform(function() {
    console.log("[*] WYX Auto-Bypass loaded");

    // Root detection bypass
    try {
        var File = Java.use("java.io.File");
        File.exists.implementation = function() {
            var path = this.getAbsolutePath();
            if (path.toLowerCase().indexOf("su") !== -1 ||
                path.toLowerCase().indexOf("magisk") !== -1) {
                return false;
            }
            return this.exists();
        };
    } catch(e) {}

    // SSL Pinning bypass
    try {
        var CP = Java.use("okhttp3.CertificatePinner");
        CP.check.overload('java.lang.String', 'java.util.List').implementation = function() {};
    } catch(e) {}

    console.log("[*] Bypasses injected successfully");
});
"@
        $bypassContent | Out-File -FilePath $bypassScript -Encoding utf8
        $FridaScript = $bypassScript
        Write-Host "[+] Auto-bypass script created: $bypassScript" -ForegroundColor Green
    }

    if (Test-Path $FridaScript) {
        $fridaScript = Join-Path $SkillRoot "scripts\frida-run.ps1"
        if (Test-Path $fridaScript) {
            Write-Host "`n[*] Starting Frida injection..." -ForegroundColor Yellow
            # 注意：这里需要用户输入包名
            $packageName = Read-Host "Enter package name (e.g., com.game.target)"
            if ($packageName) {
                pwsh -File $fridaScript -Usb -Spawn -Package $packageName -ScriptPath $FridaScript
            }
        }
    }
}

# ==================== Phase 3: 生成报告 ====================
if ($GenerateReport) {
    Write-Host "`n[Phase 3] Generating Report..." -ForegroundColor Cyan

    $reportPath = Join-Path $OutputDir "analysis_report.md"

    # 读取搜索结果
    $searchReport = Join-Path $jadxOut "..\search_report.md"
    $searchContent = ""
    if (Test-Path $searchReport) {
        $searchContent = Get-Content $searchReport -Raw
    }

    # 生成报告
    $report = @"
# WYX APK Analysis Report

## Basic Information
- **Target**: $ApkPath
- **Analysis Time**: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
- **Output Directory**: $OutputDir

## Analysis Results

### Static Analysis
\`\`\`
$($decodeOutput -replace '```', '\\\`\`\`')
\`\`\`

### Key Findings
- Package: [待填写]
- Native Libraries: $($soFiles.Count)
- Critical Logic: [待填写]

### Recommendations
1. [ ] Review static analysis results
2. [ ] Perform dynamic analysis with Frida
3. [ ] Analyze native libraries with IDA
4. [ ] Implement bypass based on findings

---
*Generated by WYX Skill v1.0*
"@

    $report | Out-File -FilePath $reportPath -Encoding utf8
    Write-Host "`n[+] Report saved: $reportPath" -ForegroundColor Green
}

# ==================== 完成 ====================
Write-Host "`n[+] Analysis complete!" -ForegroundColor Green
Write-Host "    Output: $OutputDir" -ForegroundColor White
Write-Host "`n[*] Next steps:" -ForegroundColor Cyan
Write-Host "    1. Review the analysis report" -ForegroundColor Gray
Write-Host "    2. Check search_report.md for critical logic" -ForegroundColor Gray
Write-Host "    3. Use Frida for dynamic analysis if needed" -ForegroundColor Gray
Write-Host "    4. Analyze .so files with ida-reverse skill" -ForegroundColor Gray
